// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service_bubank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bubank_Register_FullMethodName = "/pb.Bubank/Register"
	Bubank_Login_FullMethodName    = "/pb.Bubank/Login"
)

// BubankClient is the client API for Bubank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bubank service
type BubankClient interface {
	// Register rpc
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Login rpc
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type bubankClient struct {
	cc grpc.ClientConnInterface
}

func NewBubankClient(cc grpc.ClientConnInterface) BubankClient {
	return &bubankClient{cc}
}

func (c *bubankClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Bubank_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bubankClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Bubank_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BubankServer is the server API for Bubank service.
// All implementations must embed UnimplementedBubankServer
// for forward compatibility.
//
// Bubank service
type BubankServer interface {
	// Register rpc
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Login rpc
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	mustEmbedUnimplementedBubankServer()
}

// UnimplementedBubankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBubankServer struct{}

func (UnimplementedBubankServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedBubankServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedBubankServer) mustEmbedUnimplementedBubankServer() {}
func (UnimplementedBubankServer) testEmbeddedByValue()                  {}

// UnsafeBubankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BubankServer will
// result in compilation errors.
type UnsafeBubankServer interface {
	mustEmbedUnimplementedBubankServer()
}

func RegisterBubankServer(s grpc.ServiceRegistrar, srv BubankServer) {
	// If the following call panics, it indicates UnimplementedBubankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bubank_ServiceDesc, srv)
}

func _Bubank_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubankServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubank_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubankServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bubank_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BubankServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bubank_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BubankServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bubank_ServiceDesc is the grpc.ServiceDesc for Bubank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bubank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Bubank",
	HandlerType: (*BubankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Bubank_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Bubank_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_bubank.proto",
}
