// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service_graybank.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_graybank_proto protoreflect.FileDescriptor

const file_service_graybank_proto_rawDesc = "" +
	"\n" +
	"\x16service_graybank.proto\x12\x02pb\x1a\n" +
	"user.proto\x1a\x12rpc_register.proto\x1a\x0frpc_login.proto\x1a\x1cgoogle/api/annotations.proto2\x96\x01\n" +
	"\x06Bubank\x12K\n" +
	"\bRegister\x12\x13.pb.RegisterRequest\x1a\x14.pb.RegisterResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\"\f/v1/register\x12?\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\"\x11\x82\xd3\xe4\x93\x02\v\"\t/v1/loginB&Z$github.com/MaraSystems/bubank_api/pbb\x06proto3"

var file_service_graybank_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: pb.RegisterRequest
	(*LoginRequest)(nil),     // 1: pb.LoginRequest
	(*RegisterResponse)(nil), // 2: pb.RegisterResponse
	(*LoginResponse)(nil),    // 3: pb.LoginResponse
}
var file_service_graybank_proto_depIdxs = []int32{
	0, // 0: pb.Bubank.Register:input_type -> pb.RegisterRequest
	1, // 1: pb.Bubank.Login:input_type -> pb.LoginRequest
	2, // 2: pb.Bubank.Register:output_type -> pb.RegisterResponse
	3, // 3: pb.Bubank.Login:output_type -> pb.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_graybank_proto_init() }
func file_service_graybank_proto_init() {
	if File_service_graybank_proto != nil {
		return
	}
	file_user_proto_init()
	file_rpc_register_proto_init()
	file_rpc_login_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_graybank_proto_rawDesc), len(file_service_graybank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_graybank_proto_goTypes,
		DependencyIndexes: file_service_graybank_proto_depIdxs,
	}.Build()
	File_service_graybank_proto = out.File
	file_service_graybank_proto_goTypes = nil
	file_service_graybank_proto_depIdxs = nil
}
